/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package framework.mod.user.client.view;


import framework.mod.user.admin.model.tools.autoComplete.AutocompleteJComboBox;
import framework.mod.user.client.model.classes.miniSimpleTableModel_Client;
import framework.mod.user.client.model.tools.autoComplete.AutocompleteJComboBoxClt;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.InputEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author osotemi
 */
public class main_Client extends javax.swing.JFrame {

    public static TableRowSorter<TableModel> sorterClt = new TableRowSorter<TableModel>(new miniSimpleTableModel_Client());
    public static AutocompleteJComboBoxClt comboClt = null;

    /**
     * Creates new main Admin
     */
    public main_Client() {
        
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage3 = new org.edisoncor.gui.panel.PanelImage();
        btnGroupState = new javax.swing.ButtonGroup();
        PNL_title = new org.edisoncor.gui.panel.PanelImage();
        lbl_currprofile = new javax.swing.JLabel();
        PNL_menuBtn = new org.edisoncor.gui.panel.PanelImage();
        btn_backMain = new org.edisoncor.gui.button.ButtonAero();
        btn_saveJSON = new org.edisoncor.gui.button.ButtonAero();
        btn_saveXML = new org.edisoncor.gui.button.ButtonAero();
        btn_saveTXT = new org.edisoncor.gui.button.ButtonAero();
        btn_modifyClient = new javax.swing.JButton();
        btn_viewClient = new javax.swing.JButton();
        btn_deleteClient = new javax.swing.JButton();
        btn_createClient = new javax.swing.JButton();
        btn_deleteAllClient = new javax.swing.JButton();
        btn_createDummies = new javax.swing.JButton();
        PNL_footer = new org.edisoncor.gui.panel.PanelImage();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        PNL_form = new org.edisoncor.gui.panel.PanelImage();
        jScrollPane1 = new javax.swing.JScrollPane();
        PNL_drawForm = new javax.swing.JPanel();
        DC_formClt_singdate = new com.toedter.calendar.JDateChooser();
        lbl_formClt_nameERR = new javax.swing.JLabel();
        lbl_formClt_lastnameERR = new javax.swing.JLabel();
        lbl_form_passConf = new javax.swing.JLabel();
        lbl_form_bornDate = new javax.swing.JLabel();
        lbl_form_userName = new javax.swing.JLabel();
        lbl_formClt_lusernameERR = new javax.swing.JLabel();
        lbl_formClt_passERR = new javax.swing.JLabel();
        txtf_formClt_name = new javax.swing.JTextField();
        txtf_formClt_email = new javax.swing.JTextField();
        txtf_formClt_username = new javax.swing.JTextField();
        DC_formClt_borndate = new com.toedter.calendar.JDateChooser();
        JPF_fromClt_pass = new javax.swing.JPasswordField();
        btn_formClt_Avatar = new javax.swing.JButton();
        btn_formCltCreate_back = new javax.swing.JButton();
        btn_formCltCreate_create = new javax.swing.JButton();
        txtf_formClt_lastname = new javax.swing.JTextField();
        JPF_fromClt_passconf = new javax.swing.JPasswordField();
        lbl_form_pass = new javax.swing.JLabel();
        lbl_formClt_passconfERR = new javax.swing.JLabel();
        lbl_form_lastName = new javax.swing.JLabel();
        lbl_form_name = new javax.swing.JLabel();
        lbl_formClt_phoneERR = new javax.swing.JLabel();
        lbl_formClt_singdateERR = new javax.swing.JLabel();
        lbl_form_hireDate = new javax.swing.JLabel();
        lbl_form_avatar = new javax.swing.JLabel();
        lbl_form_email = new javax.swing.JLabel();
        lbl_formClt_dniERR = new javax.swing.JLabel();
        lblMainform = new javax.swing.JLabel();
        lbl_form_dni = new javax.swing.JLabel();
        lbl_formClt_emailERR = new javax.swing.JLabel();
        lbl_form_phone = new javax.swing.JLabel();
        lbl_form_state = new javax.swing.JLabel();
        lbl_form_shopAccount = new javax.swing.JLabel();
        lbl_formClt_borndateERR = new javax.swing.JLabel();
        txtf_formClt_dni = new javax.swing.JTextField();
        txtf_formClt_phone = new javax.swing.JTextField();
        CB_formClt_state = new javax.swing.JComboBox<>();
        txt_formClt_shopAccount = new javax.swing.JTextField();
        lbl_formClt_shopAccountERR = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbl_formClt_photoavatar = new javax.swing.JLabel();
        lbl_form_benefit = new javax.swing.JLabel();
        JCK_form_premium = new javax.swing.JCheckBox();
        lbl_form_clType = new javax.swing.JLabel();
        CB_formCLT_type = new javax.swing.JComboBox<>();
        PNL_mainTablePager = new javax.swing.JPanel();
        PNL_table = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TABLA_CLT = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        ANTERIOR = new javax.swing.JButton();
        SIGUIENTE = new javax.swing.JButton();
        CAJA_CLT = new javax.swing.JTextField();
        primero = new javax.swing.JButton();
        ultimo = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btn_tbl_back = new javax.swing.JButton();
        CB_tbl_entries = new javax.swing.JComboBox();
        lbl_rowBYpag = new javax.swing.JLabel();
        lbl_filtBY = new javax.swing.JLabel();
        lbl_entries = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        javax.swing.GroupLayout panelImage3Layout = new javax.swing.GroupLayout(panelImage3);
        panelImage3.setLayout(panelImage3Layout);
        panelImage3Layout.setHorizontalGroup(
            panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelImage3Layout.setVerticalGroup(
            panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1370, 780));

        PNL_title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/14650540950_fe4dc85417_o.jpg"))); // NOI18N
        PNL_title.setName(""); // NOI18N
        PNL_title.setPreferredSize(new java.awt.Dimension(0, 50));

        lbl_currprofile.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lbl_currprofile.setForeground(new java.awt.Color(153, 255, 153));
        lbl_currprofile.setText("_");
        lbl_currprofile.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout PNL_titleLayout = new javax.swing.GroupLayout(PNL_title);
        PNL_title.setLayout(PNL_titleLayout);
        PNL_titleLayout.setHorizontalGroup(
            PNL_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_currprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(792, Short.MAX_VALUE))
        );
        PNL_titleLayout.setVerticalGroup(
            PNL_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_currprofile, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(PNL_title, java.awt.BorderLayout.NORTH);

        PNL_menuBtn.setPreferredSize(new java.awt.Dimension(100, 100));

        btn_backMain.setBackground(new java.awt.Color(255, 0, 0));
        btn_backMain.setText("Inicio");

        btn_saveJSON.setBackground(new java.awt.Color(51, 255, 204));
        btn_saveJSON.setText("JSON");

        btn_saveXML.setBackground(new java.awt.Color(51, 255, 204));
        btn_saveXML.setText("XML");

        btn_saveTXT.setBackground(new java.awt.Color(51, 255, 204));
        btn_saveTXT.setText("TXT");

        btn_modifyClient.setBackground(new java.awt.Color(204, 204, 255));
        btn_modifyClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/form_icons/modify_user.png"))); // NOI18N
        btn_modifyClient.setToolTipText("Modificar Administrador");
        btn_modifyClient.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_modifyClient.setMaximumSize(new java.awt.Dimension(64, 64));
        btn_modifyClient.setMinimumSize(new java.awt.Dimension(64, 64));
        btn_modifyClient.setPreferredSize(new java.awt.Dimension(64, 64));

        btn_viewClient.setBackground(new java.awt.Color(255, 255, 255));
        btn_viewClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/form_icons/view_user.png"))); // NOI18N
        btn_viewClient.setToolTipText("Ver Administrador");
        btn_viewClient.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_viewClient.setMaximumSize(new java.awt.Dimension(64, 64));
        btn_viewClient.setMinimumSize(new java.awt.Dimension(64, 64));
        btn_viewClient.setOpaque(false);
        btn_viewClient.setPreferredSize(new java.awt.Dimension(64, 64));

        btn_deleteClient.setBackground(new java.awt.Color(255, 0, 0));
        btn_deleteClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/form_icons/delete_user.png"))); // NOI18N
        btn_deleteClient.setToolTipText("Eliminar Administrador");
        btn_deleteClient.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_deleteClient.setMaximumSize(new java.awt.Dimension(64, 64));
        btn_deleteClient.setMinimumSize(new java.awt.Dimension(64, 64));
        btn_deleteClient.setPreferredSize(new java.awt.Dimension(64, 64));

        btn_createClient.setBackground(new java.awt.Color(0, 153, 0));
        btn_createClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/form_icons/create_user.png"))); // NOI18N
        btn_createClient.setToolTipText("Crear Administrador");
        btn_createClient.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_createClient.setMaximumSize(new java.awt.Dimension(64, 64));
        btn_createClient.setMinimumSize(new java.awt.Dimension(64, 64));
        btn_createClient.setPreferredSize(new java.awt.Dimension(64, 64));

        btn_deleteAllClient.setBackground(new java.awt.Color(255, 0, 0));
        btn_deleteAllClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/form_icons/deleteAll_user.png"))); // NOI18N
        btn_deleteAllClient.setToolTipText("Eliminar todos los administradores");
        btn_deleteAllClient.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_deleteAllClient.setMaximumSize(new java.awt.Dimension(64, 64));
        btn_deleteAllClient.setMinimumSize(new java.awt.Dimension(64, 64));
        btn_deleteAllClient.setPreferredSize(new java.awt.Dimension(64, 64));

        btn_createDummies.setBackground(new java.awt.Color(0, 153, 0));
        btn_createDummies.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/form_icons/AddDummies.png"))); // NOI18N
        btn_createDummies.setToolTipText("Añadir dummies");
        btn_createDummies.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_createDummies.setMaximumSize(new java.awt.Dimension(64, 64));
        btn_createDummies.setMinimumSize(new java.awt.Dimension(64, 64));
        btn_createDummies.setPreferredSize(new java.awt.Dimension(64, 64));

        javax.swing.GroupLayout PNL_menuBtnLayout = new javax.swing.GroupLayout(PNL_menuBtn);
        PNL_menuBtn.setLayout(PNL_menuBtnLayout);
        PNL_menuBtnLayout.setHorizontalGroup(
            PNL_menuBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_backMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_saveJSON, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_saveXML, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_saveTXT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PNL_menuBtnLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(PNL_menuBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_viewClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_modifyClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_createClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_deleteClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_deleteAllClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_createDummies, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PNL_menuBtnLayout.setVerticalGroup(
            PNL_menuBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_menuBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_viewClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_modifyClient, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_createClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_deleteClient, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_createDummies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_deleteAllClient, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btn_saveXML, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btn_saveTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_saveJSON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_backMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(PNL_menuBtn, java.awt.BorderLayout.WEST);

        PNL_footer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/4809986809_aa94ea96b3_o.jpg"))); // NOI18N
        PNL_footer.setPreferredSize(new java.awt.Dimension(1410, 30));

        jLabel4.setForeground(new java.awt.Color(153, 255, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Aviso legal");
        jLabel4.setToolTipText("");

        jLabel5.setForeground(new java.awt.Color(153, 255, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Powered by @osotemi");
        jLabel5.setToolTipText("");

        jLabel14.setForeground(new java.awt.Color(153, 255, 153));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Icons designed by Freepik");
        jLabel14.setToolTipText("");

        javax.swing.GroupLayout PNL_footerLayout = new javax.swing.GroupLayout(PNL_footer);
        PNL_footer.setLayout(PNL_footerLayout);
        PNL_footerLayout.setHorizontalGroup(
            PNL_footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNL_footerLayout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(355, Short.MAX_VALUE))
        );
        PNL_footerLayout.setVerticalGroup(
            PNL_footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_footerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PNL_footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel14))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(PNL_footer, java.awt.BorderLayout.PAGE_END);

        PNL_form.setAutoscrolls(true);
        PNL_form.setMinimumSize(new java.awt.Dimension(0, 0));
        PNL_form.setName(""); // NOI18N
        PNL_form.setPreferredSize(new java.awt.Dimension(500, 600));

        PNL_drawForm.setAutoscrolls(true);
        PNL_drawForm.setPreferredSize(new java.awt.Dimension(500, 535));

        DC_formClt_singdate.setDateFormatString("dd/MM/yyyy");

        lbl_formClt_nameERR.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_formClt_nameERR.setText(" ");

        lbl_formClt_lastnameERR.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_formClt_lastnameERR.setText(" ");

        lbl_form_passConf.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_form_passConf.setText("Confirmar Contraseña");

        lbl_form_bornDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_form_bornDate.setText("Fecha de nacimiento");

        lbl_form_userName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_form_userName.setText("Nombre de usuario");

        lbl_formClt_lusernameERR.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_formClt_lusernameERR.setText(" ");
        lbl_formClt_lusernameERR.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lbl_formClt_passERR.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_formClt_passERR.setText(" ");

        txtf_formClt_name.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        txtf_formClt_name.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtf_formClt_name.setToolTipText("Nombre...");
        txtf_formClt_name.setBorder(null);
        txtf_formClt_name.setNextFocusableComponent(txtf_formClt_lastname);
        txtf_formClt_name.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        txtf_formClt_email.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        txtf_formClt_email.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtf_formClt_email.setToolTipText("Correo electrónico");
        txtf_formClt_email.setBorder(null);
        txtf_formClt_email.setNextFocusableComponent(txtf_formClt_phone);

        txtf_formClt_username.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        txtf_formClt_username.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtf_formClt_username.setToolTipText(" Nombre del administrador...");
        txtf_formClt_username.setBorder(null);
        txtf_formClt_username.setNextFocusableComponent(JPF_fromClt_pass);

        DC_formClt_borndate.setDateFormatString("dd/MM/yyyy");
        DC_formClt_borndate.setNextFocusableComponent(txtf_formClt_username);

        JPF_fromClt_pass.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        JPF_fromClt_pass.setToolTipText("Contraseña...");
        JPF_fromClt_pass.setBorder(null);
        JPF_fromClt_pass.setNextFocusableComponent(JPF_fromClt_passconf);
        JPF_fromClt_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPF_fromClt_passActionPerformed(evt);
            }
        });

        btn_formClt_Avatar.setText("Cargar Imagen");
        btn_formClt_Avatar.setBorderPainted(false);

        btn_formCltCreate_back.setText("Volver");

        btn_formCltCreate_create.setText("Crear");

        txtf_formClt_lastname.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        txtf_formClt_lastname.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtf_formClt_lastname.setToolTipText("Apellidos...");
        txtf_formClt_lastname.setBorder(null);
        txtf_formClt_lastname.setNextFocusableComponent(txtf_formClt_email);

        JPF_fromClt_passconf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        JPF_fromClt_passconf.setToolTipText("Confirmar contraseña...");
        JPF_fromClt_passconf.setBorder(null);
        JPF_fromClt_passconf.setNextFocusableComponent(btn_formClt_Avatar);
        JPF_fromClt_passconf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPF_fromClt_passconfActionPerformed(evt);
            }
        });

        lbl_form_pass.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_form_pass.setText("Contraseña");

        lbl_formClt_passconfERR.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_formClt_passconfERR.setText(" ");

        lbl_form_lastName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_form_lastName.setText("Apellidos");

        lbl_form_name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_form_name.setText("Nombre");

        lbl_formClt_phoneERR.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_formClt_phoneERR.setText(" ");

        lbl_formClt_singdateERR.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_formClt_singdateERR.setText(" ");

        lbl_form_hireDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_form_hireDate.setText("Fecha de alta");

        lbl_form_avatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_form_avatar.setText("Imagen de perfil");

        lbl_form_email.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_form_email.setText("Correo electrónico");

        lbl_formClt_dniERR.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_formClt_dniERR.setText(" ");

        lblMainform.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMainform.setText("Formulario de Cliente");

        lbl_form_dni.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_form_dni.setText("DNI");

        lbl_formClt_emailERR.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_formClt_emailERR.setText(" ");

        lbl_form_phone.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_form_phone.setText("Teléfono");

        lbl_form_state.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_form_state.setText("Estado");

        lbl_form_shopAccount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_form_shopAccount.setText("Compras");

        lbl_formClt_borndateERR.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_formClt_borndateERR.setText(" ");

        txtf_formClt_dni.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        txtf_formClt_dni.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtf_formClt_dni.setBorder(null);
        txtf_formClt_dni.setNextFocusableComponent(DC_formClt_borndate);

        txtf_formClt_phone.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        txtf_formClt_phone.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtf_formClt_phone.setBorder(null);
        txtf_formClt_phone.setNextFocusableComponent(txtf_formClt_dni);

        CB_formClt_state.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Online", "Offline", "Loged" }));
        CB_formClt_state.setSelectedItem("Offline");

        txt_formClt_shopAccount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_formClt_shopAccount.setText("0");

        lbl_formClt_shopAccountERR.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_formClt_shopAccountERR.setText(" ");

        lbl_formClt_photoavatar.setBackground(new java.awt.Color(255, 255, 255));
        lbl_formClt_photoavatar.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        lbl_formClt_photoavatar.setOpaque(true);

        lbl_form_benefit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_form_benefit.setText(" ");

        JCK_form_premium.setText("PREMIUM");

        lbl_form_clType.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_form_clType.setText(" Tipo de cliente");

        CB_formCLT_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chrome", "Silver", "Gold", "Platinum" }));

        javax.swing.GroupLayout PNL_drawFormLayout = new javax.swing.GroupLayout(PNL_drawForm);
        PNL_drawForm.setLayout(PNL_drawFormLayout);
        PNL_drawFormLayout.setHorizontalGroup(
            PNL_drawFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_drawFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PNL_drawFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PNL_drawFormLayout.createSequentialGroup()
                        .addGroup(PNL_drawFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PNL_drawFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_form_avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_formClt_Avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_form_hireDate, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_formClt_borndateERR, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DC_formClt_borndate, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(PNL_drawFormLayout.createSequentialGroup()
                                    .addGap(37, 37, 37)
                                    .addComponent(lbl_formClt_photoavatar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lbl_form_bornDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DC_formClt_singdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_formClt_singdateERR, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_form_state, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PNL_drawFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_form_passConf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JPF_fromClt_passconf)
                            .addComponent(lbl_formClt_passconfERR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_form_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtf_formClt_name)
                            .addComponent(lbl_formClt_nameERR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_form_lastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtf_formClt_lastname)
                            .addComponent(lbl_formClt_lastnameERR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_formClt_passERR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JPF_fromClt_pass)
                            .addComponent(lbl_formClt_lusernameERR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_form_pass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtf_formClt_username)
                            .addComponent(lbl_form_userName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_form_email, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(JCK_form_premium, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PNL_drawFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8)))
                    .addComponent(lblMainform, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PNL_drawFormLayout.createSequentialGroup()
                        .addGroup(PNL_drawFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_formCltCreate_back, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(CB_formClt_state, javax.swing.GroupLayout.Alignment.TRAILING, 0, 203, Short.MAX_VALUE)
                            .addComponent(lbl_form_shopAccount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(txt_formClt_shopAccount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(lbl_formClt_shopAccountERR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(lbl_form_benefit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(lbl_form_clType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(CB_formCLT_type, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PNL_drawFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_formClt_dniERR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_form_dni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtf_formClt_dni)
                            .addComponent(lbl_formClt_phoneERR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtf_formClt_email)
                            .addComponent(lbl_formClt_emailERR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtf_formClt_phone)
                            .addComponent(lbl_form_phone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_formCltCreate_create, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 57, Short.MAX_VALUE))
        );
        PNL_drawFormLayout.setVerticalGroup(
            PNL_drawFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_drawFormLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PNL_drawFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PNL_drawFormLayout.createSequentialGroup()
                        .addComponent(lblMainform, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PNL_drawFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PNL_drawFormLayout.createSequentialGroup()
                                .addComponent(lbl_form_userName)
                                .addGap(0, 0, 0)
                                .addComponent(txtf_formClt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_formClt_lusernameERR, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(lbl_form_pass)
                                .addGap(0, 0, 0)
                                .addComponent(JPF_fromClt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(lbl_formClt_passERR, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(lbl_form_passConf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JPF_fromClt_passconf, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(lbl_formClt_passconfERR, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JCK_form_premium)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PNL_drawFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_form_name)
                                    .addComponent(lbl_form_bornDate)))
                            .addGroup(PNL_drawFormLayout.createSequentialGroup()
                                .addComponent(lbl_form_avatar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_formClt_photoavatar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_formClt_Avatar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PNL_drawFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PNL_drawFormLayout.createSequentialGroup()
                                .addComponent(txtf_formClt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_formClt_nameERR, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(PNL_drawFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_form_lastName)
                                    .addComponent(lbl_form_hireDate)))
                            .addGroup(PNL_drawFormLayout.createSequentialGroup()
                                .addComponent(DC_formClt_borndate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_formClt_borndateERR)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PNL_drawFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtf_formClt_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DC_formClt_singdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PNL_drawFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_formClt_lastnameERR, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_formClt_singdateERR, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PNL_drawFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_form_email)
                            .addComponent(lbl_form_state))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PNL_drawFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtf_formClt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CB_formClt_state))
                        .addGap(0, 0, 0)
                        .addComponent(lbl_formClt_emailERR, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PNL_drawFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_form_phone)
                            .addComponent(lbl_form_shopAccount))
                        .addGap(0, 0, 0)
                        .addGroup(PNL_drawFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtf_formClt_phone, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                            .addComponent(txt_formClt_shopAccount))
                        .addGap(0, 0, 0)
                        .addGroup(PNL_drawFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_formClt_phoneERR, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_formClt_shopAccountERR))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PNL_drawFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_form_dni)
                            .addComponent(lbl_form_clType))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PNL_drawFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtf_formClt_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CB_formCLT_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PNL_drawFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_formClt_dniERR, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_form_benefit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PNL_drawFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_formCltCreate_back)
                            .addComponent(btn_formCltCreate_create)))
                    .addGroup(PNL_drawFormLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(PNL_drawForm);

        javax.swing.GroupLayout PNL_formLayout = new javax.swing.GroupLayout(PNL_form);
        PNL_form.setLayout(PNL_formLayout);
        PNL_formLayout.setHorizontalGroup(
            PNL_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNL_formLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                .addContainerGap())
        );
        PNL_formLayout.setVerticalGroup(
            PNL_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNL_formLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE))
        );

        getContentPane().add(PNL_form, java.awt.BorderLayout.CENTER);

        PNL_table.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TABLA_CLT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(TABLA_CLT);

        javax.swing.GroupLayout PNL_tableLayout = new javax.swing.GroupLayout(PNL_table);
        PNL_table.setLayout(PNL_tableLayout);
        PNL_tableLayout.setHorizontalGroup(
            PNL_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_tableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PNL_tableLayout.setVerticalGroup(
            PNL_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_tableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ANTERIOR.setText("<");
        jPanel3.add(ANTERIOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        SIGUIENTE.setText(">");
        jPanel3.add(SIGUIENTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        CAJA_CLT.setEditable(false);
        CAJA_CLT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CAJA_CLT.setPreferredSize(new java.awt.Dimension(140, 20));
        jPanel3.add(CAJA_CLT, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 80, 30));

        primero.setText("|<");
        jPanel3.add(primero, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        ultimo.setText(">|");
        jPanel3.add(ultimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        btn_tbl_back.setText("V");

        CB_tbl_entries.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "5", "10", "15", "20", "50", "100" }));

        lbl_rowBYpag.setText("Show entries:");

        lbl_filtBY.setText("F");

        lbl_entries.setText("n");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 175, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PNL_mainTablePagerLayout = new javax.swing.GroupLayout(PNL_mainTablePager);
        PNL_mainTablePager.setLayout(PNL_mainTablePagerLayout);
        PNL_mainTablePagerLayout.setHorizontalGroup(
            PNL_mainTablePagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_mainTablePagerLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PNL_mainTablePagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_rowBYpag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PNL_mainTablePagerLayout.createSequentialGroup()
                        .addComponent(CB_tbl_entries, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(PNL_mainTablePagerLayout.createSequentialGroup()
                .addGroup(PNL_mainTablePagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PNL_mainTablePagerLayout.createSequentialGroup()
                        .addComponent(PNL_table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PNL_mainTablePagerLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lbl_filtBY, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_entries, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_tbl_back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(PNL_mainTablePagerLayout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PNL_mainTablePagerLayout.setVerticalGroup(
            PNL_mainTablePagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNL_mainTablePagerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PNL_table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PNL_mainTablePagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PNL_mainTablePagerLayout.createSequentialGroup()
                        .addComponent(lbl_rowBYpag)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CB_tbl_entries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PNL_mainTablePagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_tbl_back)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PNL_mainTablePagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lbl_filtBY, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addComponent(lbl_entries, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(33, 33, 33))
        );

        getContentPane().add(PNL_mainTablePager, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JPF_fromClt_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPF_fromClt_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPF_fromClt_passActionPerformed

    private void JPF_fromClt_passconfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPF_fromClt_passconfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPF_fromClt_passconfActionPerformed
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton ANTERIOR;
    public static javax.swing.JTextField CAJA_CLT;
    public static javax.swing.JComboBox<String> CB_formCLT_type;
    public static javax.swing.JComboBox<String> CB_formClt_state;
    public static javax.swing.JComboBox CB_tbl_entries;
    public static com.toedter.calendar.JDateChooser DC_formClt_borndate;
    public static com.toedter.calendar.JDateChooser DC_formClt_singdate;
    public static javax.swing.JCheckBox JCK_form_premium;
    public static javax.swing.JPasswordField JPF_fromClt_pass;
    public static javax.swing.JPasswordField JPF_fromClt_passconf;
    public static javax.swing.JPanel PNL_drawForm;
    public static org.edisoncor.gui.panel.PanelImage PNL_footer;
    public static org.edisoncor.gui.panel.PanelImage PNL_form;
    public static javax.swing.JPanel PNL_mainTablePager;
    public static org.edisoncor.gui.panel.PanelImage PNL_menuBtn;
    public static javax.swing.JPanel PNL_table;
    public static org.edisoncor.gui.panel.PanelImage PNL_title;
    public static javax.swing.JButton SIGUIENTE;
    public static javax.swing.JTable TABLA_CLT;
    public static javax.swing.ButtonGroup btnGroupState;
    public static org.edisoncor.gui.button.ButtonAero btn_backMain;
    public static javax.swing.JButton btn_createClient;
    public static javax.swing.JButton btn_createDummies;
    public static javax.swing.JButton btn_deleteAllClient;
    public static javax.swing.JButton btn_deleteClient;
    public static javax.swing.JButton btn_formCltCreate_back;
    public static javax.swing.JButton btn_formCltCreate_create;
    public static javax.swing.JButton btn_formClt_Avatar;
    public static javax.swing.JButton btn_modifyClient;
    public static org.edisoncor.gui.button.ButtonAero btn_saveJSON;
    public static org.edisoncor.gui.button.ButtonAero btn_saveTXT;
    public static org.edisoncor.gui.button.ButtonAero btn_saveXML;
    public static javax.swing.JButton btn_tbl_back;
    public static javax.swing.JButton btn_viewClient;
    public static javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel14;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel8;
    public static javax.swing.JPanel jPanel3;
    public static javax.swing.JPanel jPanel4;
    public static javax.swing.JPanel jPanel5;
    public static javax.swing.JPanel jPanel6;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JLabel lblMainform;
    public static javax.swing.JLabel lbl_currprofile;
    public static javax.swing.JLabel lbl_entries;
    public static javax.swing.JLabel lbl_filtBY;
    public static javax.swing.JLabel lbl_formClt_borndateERR;
    public static javax.swing.JLabel lbl_formClt_dniERR;
    public static javax.swing.JLabel lbl_formClt_emailERR;
    public static javax.swing.JLabel lbl_formClt_lastnameERR;
    public static javax.swing.JLabel lbl_formClt_lusernameERR;
    public static javax.swing.JLabel lbl_formClt_nameERR;
    public static javax.swing.JLabel lbl_formClt_passERR;
    public static javax.swing.JLabel lbl_formClt_passconfERR;
    public static javax.swing.JLabel lbl_formClt_phoneERR;
    public static javax.swing.JLabel lbl_formClt_photoavatar;
    public static javax.swing.JLabel lbl_formClt_shopAccountERR;
    public static javax.swing.JLabel lbl_formClt_singdateERR;
    public static javax.swing.JLabel lbl_form_avatar;
    public static javax.swing.JLabel lbl_form_benefit;
    public static javax.swing.JLabel lbl_form_bornDate;
    public static javax.swing.JLabel lbl_form_clType;
    public static javax.swing.JLabel lbl_form_dni;
    public static javax.swing.JLabel lbl_form_email;
    public static javax.swing.JLabel lbl_form_hireDate;
    public static javax.swing.JLabel lbl_form_lastName;
    public static javax.swing.JLabel lbl_form_name;
    public static javax.swing.JLabel lbl_form_pass;
    public static javax.swing.JLabel lbl_form_passConf;
    public static javax.swing.JLabel lbl_form_phone;
    public static javax.swing.JLabel lbl_form_shopAccount;
    public static javax.swing.JLabel lbl_form_state;
    public static javax.swing.JLabel lbl_form_userName;
    public static javax.swing.JLabel lbl_rowBYpag;
    public static org.edisoncor.gui.panel.PanelImage panelImage3;
    public static javax.swing.JButton primero;
    public static javax.swing.JTextField txt_formClt_shopAccount;
    public static javax.swing.JTextField txtf_formClt_dni;
    public static javax.swing.JTextField txtf_formClt_email;
    public static javax.swing.JTextField txtf_formClt_lastname;
    public static javax.swing.JTextField txtf_formClt_name;
    public static javax.swing.JTextField txtf_formClt_phone;
    public static javax.swing.JTextField txtf_formClt_username;
    public static javax.swing.JButton ultimo;
    // End of variables declaration//GEN-END:variables

    public static class sorter {

        public sorter() {
        }
    }
}
