/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package framework.mod.user.registered.view;


import framework.mod.user.registered.model.classes.miniSimpleTableModelReg;
import framework.mod.user.registered.model.tools.autoComplete.AutoCompleteJComboBoxReg;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.InputEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author osotemi
 */
public class main_Reg extends javax.swing.JFrame {

    public static TableRowSorter<TableModel> sorterReg = new TableRowSorter<TableModel>(new miniSimpleTableModelReg());
    public static AutoCompleteJComboBoxReg comboReg = null;

    /**
     * Creates new main Admin
     */
    public main_Reg() {
        
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage3 = new org.edisoncor.gui.panel.PanelImage();
        btnGroupState = new javax.swing.ButtonGroup();
        PNL_title = new org.edisoncor.gui.panel.PanelImage();
        PNL_menuBtn = new org.edisoncor.gui.panel.PanelImage();
        btn_backMain = new org.edisoncor.gui.button.ButtonAero();
        btn_saveJSON = new org.edisoncor.gui.button.ButtonAero();
        btn_saveXML = new org.edisoncor.gui.button.ButtonAero();
        btn_saveTXT = new org.edisoncor.gui.button.ButtonAero();
        btn_modifyReg = new javax.swing.JButton();
        btn_viewReg = new javax.swing.JButton();
        btn_deleteReg = new javax.swing.JButton();
        btn_createReg = new javax.swing.JButton();
        btn_deleteAllReg = new javax.swing.JButton();
        btn_createDummies = new javax.swing.JButton();
        PNL_footer = new org.edisoncor.gui.panel.PanelImage();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        PNL_form = new org.edisoncor.gui.panel.PanelImage();
        jScrollPane1 = new javax.swing.JScrollPane();
        PNL_drawForm = new javax.swing.JPanel();
        lbl_formReg_nameERR = new javax.swing.JLabel();
        lbl_formReg_lastnameERR = new javax.swing.JLabel();
        lbl_form_passConf = new javax.swing.JLabel();
        lbl_form_bornDate = new javax.swing.JLabel();
        lbl_form_userName = new javax.swing.JLabel();
        lbl_formReg_usernameERR = new javax.swing.JLabel();
        lbl_formReg_passERR = new javax.swing.JLabel();
        txtf_formReg_name = new javax.swing.JTextField();
        txtf_formReg_email = new javax.swing.JTextField();
        txtf_formReg_username = new javax.swing.JTextField();
        DC_formReg_borndate = new com.toedter.calendar.JDateChooser();
        JPF_fromReg_pass = new javax.swing.JPasswordField();
        btn_formReg_Avatar = new javax.swing.JButton();
        btn_formRegCreate_back = new javax.swing.JButton();
        btn_formRegCreate_create = new javax.swing.JButton();
        txtf_formReg_lastname = new javax.swing.JTextField();
        JPF_fromReg_passconf = new javax.swing.JPasswordField();
        lbl_form_pass = new javax.swing.JLabel();
        lbl_formReg_passconfERR = new javax.swing.JLabel();
        lbl_form_lastName = new javax.swing.JLabel();
        lbl_form_name = new javax.swing.JLabel();
        lbl_formReg_phoneERR = new javax.swing.JLabel();
        lbl_form_avatar = new javax.swing.JLabel();
        lbl_form_email = new javax.swing.JLabel();
        lbl_formReg_dniERR = new javax.swing.JLabel();
        lblMainform = new javax.swing.JLabel();
        lbl_form_dni = new javax.swing.JLabel();
        lbl_formReg_emailERR = new javax.swing.JLabel();
        lbl_form_phone = new javax.swing.JLabel();
        lbl_form_state = new javax.swing.JLabel();
        lbl_form_activity = new javax.swing.JLabel();
        lbl_formReg_borndateERR = new javax.swing.JLabel();
        txtf_formReg_dni = new javax.swing.JTextField();
        txtf_formReg_phone = new javax.swing.JTextField();
        CB_formReg_state = new javax.swing.JComboBox<>();
        txt_formReg_activity = new javax.swing.JTextField();
        lbl_formReg_activityERR = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbl_formReg_photoavatar = new javax.swing.JLabel();
        PNL_mainTablePager = new javax.swing.JPanel();
        PNL_table = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TABLA_REG = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        ANTERIOR = new javax.swing.JButton();
        SIGUIENTE = new javax.swing.JButton();
        CAJA_REG = new javax.swing.JTextField();
        primero = new javax.swing.JButton();
        ultimo = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btn_tbl_back = new javax.swing.JButton();
        CB_tbl_entries = new javax.swing.JComboBox();
        lbl_rowBYpag = new javax.swing.JLabel();
        lbl_filtBY = new javax.swing.JLabel();
        lbl_entries = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        javax.swing.GroupLayout panelImage3Layout = new javax.swing.GroupLayout(panelImage3);
        panelImage3.setLayout(panelImage3Layout);
        panelImage3Layout.setHorizontalGroup(
            panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelImage3Layout.setVerticalGroup(
            panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1370, 780));

        PNL_title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/14650540950_fe4dc85417_o.jpg"))); // NOI18N
        PNL_title.setName(""); // NOI18N
        PNL_title.setPreferredSize(new java.awt.Dimension(0, 50));

        javax.swing.GroupLayout PNL_titleLayout = new javax.swing.GroupLayout(PNL_title);
        PNL_title.setLayout(PNL_titleLayout);
        PNL_titleLayout.setHorizontalGroup(
            PNL_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1410, Short.MAX_VALUE)
        );
        PNL_titleLayout.setVerticalGroup(
            PNL_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(PNL_title, java.awt.BorderLayout.NORTH);

        PNL_menuBtn.setPreferredSize(new java.awt.Dimension(100, 100));

        btn_backMain.setBackground(new java.awt.Color(255, 0, 0));
        btn_backMain.setText("Inicio");

        btn_saveJSON.setBackground(new java.awt.Color(51, 255, 204));
        btn_saveJSON.setText("JSON");

        btn_saveXML.setBackground(new java.awt.Color(51, 255, 204));
        btn_saveXML.setText("XML");

        btn_saveTXT.setBackground(new java.awt.Color(51, 255, 204));
        btn_saveTXT.setText("TXT");

        btn_modifyReg.setBackground(new java.awt.Color(204, 204, 255));
        btn_modifyReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/form_icons/modify_user.png"))); // NOI18N
        btn_modifyReg.setToolTipText("Modificar Administrador");
        btn_modifyReg.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_modifyReg.setMaximumSize(new java.awt.Dimension(64, 64));
        btn_modifyReg.setMinimumSize(new java.awt.Dimension(64, 64));
        btn_modifyReg.setPreferredSize(new java.awt.Dimension(64, 64));

        btn_viewReg.setBackground(new java.awt.Color(255, 255, 255));
        btn_viewReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/form_icons/view_user.png"))); // NOI18N
        btn_viewReg.setToolTipText("Ver Administrador");
        btn_viewReg.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_viewReg.setMaximumSize(new java.awt.Dimension(64, 64));
        btn_viewReg.setMinimumSize(new java.awt.Dimension(64, 64));
        btn_viewReg.setOpaque(false);
        btn_viewReg.setPreferredSize(new java.awt.Dimension(64, 64));

        btn_deleteReg.setBackground(new java.awt.Color(255, 0, 0));
        btn_deleteReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/form_icons/delete_user.png"))); // NOI18N
        btn_deleteReg.setToolTipText("Eliminar Administrador");
        btn_deleteReg.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_deleteReg.setMaximumSize(new java.awt.Dimension(64, 64));
        btn_deleteReg.setMinimumSize(new java.awt.Dimension(64, 64));
        btn_deleteReg.setPreferredSize(new java.awt.Dimension(64, 64));

        btn_createReg.setBackground(new java.awt.Color(0, 153, 0));
        btn_createReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/form_icons/create_user.png"))); // NOI18N
        btn_createReg.setToolTipText("Crear Administrador");
        btn_createReg.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_createReg.setMaximumSize(new java.awt.Dimension(64, 64));
        btn_createReg.setMinimumSize(new java.awt.Dimension(64, 64));
        btn_createReg.setPreferredSize(new java.awt.Dimension(64, 64));

        btn_deleteAllReg.setBackground(new java.awt.Color(255, 0, 0));
        btn_deleteAllReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/form_icons/deleteAll_user.png"))); // NOI18N
        btn_deleteAllReg.setToolTipText("Eliminar todos los administradores");
        btn_deleteAllReg.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_deleteAllReg.setMaximumSize(new java.awt.Dimension(64, 64));
        btn_deleteAllReg.setMinimumSize(new java.awt.Dimension(64, 64));
        btn_deleteAllReg.setPreferredSize(new java.awt.Dimension(64, 64));

        btn_createDummies.setBackground(new java.awt.Color(0, 153, 0));
        btn_createDummies.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/form_icons/AddDummies.png"))); // NOI18N
        btn_createDummies.setToolTipText("Añadir dummies");
        btn_createDummies.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_createDummies.setMaximumSize(new java.awt.Dimension(64, 64));
        btn_createDummies.setMinimumSize(new java.awt.Dimension(64, 64));
        btn_createDummies.setPreferredSize(new java.awt.Dimension(64, 64));

        javax.swing.GroupLayout PNL_menuBtnLayout = new javax.swing.GroupLayout(PNL_menuBtn);
        PNL_menuBtn.setLayout(PNL_menuBtnLayout);
        PNL_menuBtnLayout.setHorizontalGroup(
            PNL_menuBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_backMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_saveJSON, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_saveXML, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_saveTXT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PNL_menuBtnLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(PNL_menuBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_viewReg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_modifyReg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_createReg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_deleteReg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_deleteAllReg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_createDummies, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PNL_menuBtnLayout.setVerticalGroup(
            PNL_menuBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_menuBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_viewReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_modifyReg, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_createReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_deleteReg, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_createDummies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_deleteAllReg, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btn_saveXML, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btn_saveTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_saveJSON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_backMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(PNL_menuBtn, java.awt.BorderLayout.WEST);

        PNL_footer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/4809986809_aa94ea96b3_o.jpg"))); // NOI18N
        PNL_footer.setPreferredSize(new java.awt.Dimension(1410, 30));

        jLabel4.setForeground(new java.awt.Color(153, 255, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Aviso legal");
        jLabel4.setToolTipText("");

        jLabel5.setForeground(new java.awt.Color(153, 255, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Powered by @osotemi");
        jLabel5.setToolTipText("");

        jLabel14.setForeground(new java.awt.Color(153, 255, 153));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Icons designed by Freepik");
        jLabel14.setToolTipText("");

        javax.swing.GroupLayout PNL_footerLayout = new javax.swing.GroupLayout(PNL_footer);
        PNL_footer.setLayout(PNL_footerLayout);
        PNL_footerLayout.setHorizontalGroup(
            PNL_footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNL_footerLayout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(355, Short.MAX_VALUE))
        );
        PNL_footerLayout.setVerticalGroup(
            PNL_footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_footerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PNL_footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel14))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(PNL_footer, java.awt.BorderLayout.PAGE_END);

        PNL_form.setAutoscrolls(true);
        PNL_form.setMinimumSize(new java.awt.Dimension(0, 0));
        PNL_form.setName(""); // NOI18N
        PNL_form.setPreferredSize(new java.awt.Dimension(500, 600));

        PNL_drawForm.setAutoscrolls(true);
        PNL_drawForm.setPreferredSize(new java.awt.Dimension(500, 535));

        lbl_formReg_nameERR.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_formReg_nameERR.setText(" ");

        lbl_formReg_lastnameERR.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_formReg_lastnameERR.setText(" ");

        lbl_form_passConf.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_form_passConf.setText("Confirmar Contraseña");

        lbl_form_bornDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_form_bornDate.setText("Fecha de nacimiento");

        lbl_form_userName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_form_userName.setText("Nombre de usuario");

        lbl_formReg_usernameERR.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_formReg_usernameERR.setText(" ");
        lbl_formReg_usernameERR.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lbl_formReg_passERR.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_formReg_passERR.setText(" ");

        txtf_formReg_name.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        txtf_formReg_name.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtf_formReg_name.setToolTipText("Nombre...");
        txtf_formReg_name.setBorder(null);
        txtf_formReg_name.setNextFocusableComponent(txtf_formReg_lastname);
        txtf_formReg_name.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        txtf_formReg_email.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        txtf_formReg_email.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtf_formReg_email.setToolTipText("Correo electrónico");
        txtf_formReg_email.setBorder(null);
        txtf_formReg_email.setNextFocusableComponent(txtf_formReg_phone);

        txtf_formReg_username.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        txtf_formReg_username.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtf_formReg_username.setToolTipText(" Nombre del administrador...");
        txtf_formReg_username.setBorder(null);
        txtf_formReg_username.setNextFocusableComponent(JPF_fromReg_pass);

        DC_formReg_borndate.setDateFormatString("dd/MM/yyyy");
        DC_formReg_borndate.setNextFocusableComponent(txtf_formReg_username);

        JPF_fromReg_pass.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        JPF_fromReg_pass.setToolTipText("Contraseña...");
        JPF_fromReg_pass.setBorder(null);
        JPF_fromReg_pass.setNextFocusableComponent(JPF_fromReg_passconf);

        btn_formReg_Avatar.setText("Cargar Imagen");
        btn_formReg_Avatar.setBorderPainted(false);

        btn_formRegCreate_back.setText("Volver");

        btn_formRegCreate_create.setText("Crear");

        txtf_formReg_lastname.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        txtf_formReg_lastname.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtf_formReg_lastname.setToolTipText("Apellidos...");
        txtf_formReg_lastname.setBorder(null);
        txtf_formReg_lastname.setNextFocusableComponent(txtf_formReg_email);

        JPF_fromReg_passconf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        JPF_fromReg_passconf.setToolTipText("Confirmar contraseña...");
        JPF_fromReg_passconf.setBorder(null);
        JPF_fromReg_passconf.setNextFocusableComponent(btn_formReg_Avatar);

        lbl_form_pass.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_form_pass.setText("Contraseña");

        lbl_formReg_passconfERR.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_formReg_passconfERR.setText(" ");

        lbl_form_lastName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_form_lastName.setText("Apellidos");

        lbl_form_name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_form_name.setText("Nombre");

        lbl_formReg_phoneERR.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_formReg_phoneERR.setText(" ");

        lbl_form_avatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_form_avatar.setText("Imagen de perfil");

        lbl_form_email.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_form_email.setText("Correo electrónico");

        lbl_formReg_dniERR.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_formReg_dniERR.setText(" ");

        lblMainform.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMainform.setText("Formulario de Usuario Registrado");

        lbl_form_dni.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_form_dni.setText("DNI");

        lbl_formReg_emailERR.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_formReg_emailERR.setText(" ");

        lbl_form_phone.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_form_phone.setText("Teléfono");

        lbl_form_state.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_form_state.setText("Estado");

        lbl_form_activity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_form_activity.setText("Actividad");

        lbl_formReg_borndateERR.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_formReg_borndateERR.setText(" ");

        txtf_formReg_dni.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        txtf_formReg_dni.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtf_formReg_dni.setBorder(null);
        txtf_formReg_dni.setNextFocusableComponent(DC_formReg_borndate);

        txtf_formReg_phone.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        txtf_formReg_phone.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtf_formReg_phone.setBorder(null);
        txtf_formReg_phone.setNextFocusableComponent(txtf_formReg_dni);

        CB_formReg_state.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Online", "Offline", "Loged" }));
        CB_formReg_state.setSelectedItem("Offline");

        txt_formReg_activity.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_formReg_activity.setText("0");

        lbl_formReg_activityERR.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_formReg_activityERR.setText(" ");

        lbl_formReg_photoavatar.setBackground(new java.awt.Color(255, 255, 255));
        lbl_formReg_photoavatar.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        lbl_formReg_photoavatar.setOpaque(true);

        javax.swing.GroupLayout PNL_drawFormLayout = new javax.swing.GroupLayout(PNL_drawForm);
        PNL_drawForm.setLayout(PNL_drawFormLayout);
        PNL_drawFormLayout.setHorizontalGroup(
            PNL_drawFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_drawFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PNL_drawFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PNL_drawFormLayout.createSequentialGroup()
                        .addGroup(PNL_drawFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PNL_drawFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_form_avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_formReg_Avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_formReg_borndateERR, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DC_formReg_borndate, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(PNL_drawFormLayout.createSequentialGroup()
                                    .addGap(37, 37, 37)
                                    .addComponent(lbl_formReg_photoavatar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lbl_form_bornDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_form_state, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PNL_drawFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_form_passConf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JPF_fromReg_passconf)
                            .addComponent(lbl_formReg_passconfERR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_form_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtf_formReg_name)
                            .addComponent(lbl_formReg_nameERR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_form_lastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtf_formReg_lastname)
                            .addComponent(lbl_formReg_lastnameERR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_formReg_passERR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JPF_fromReg_pass)
                            .addComponent(lbl_formReg_usernameERR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_form_pass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtf_formReg_username)
                            .addComponent(lbl_form_userName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_form_email, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PNL_drawFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8)))
                    .addComponent(lblMainform, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PNL_drawFormLayout.createSequentialGroup()
                        .addGroup(PNL_drawFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_formRegCreate_back, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CB_formReg_state, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_form_activity, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_formReg_activity, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_formReg_activityERR, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PNL_drawFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_formReg_dniERR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_form_dni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtf_formReg_dni)
                            .addComponent(lbl_formReg_phoneERR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtf_formReg_email)
                            .addComponent(lbl_formReg_emailERR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtf_formReg_phone)
                            .addComponent(lbl_form_phone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_formRegCreate_create, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 57, Short.MAX_VALUE))
        );
        PNL_drawFormLayout.setVerticalGroup(
            PNL_drawFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_drawFormLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PNL_drawFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PNL_drawFormLayout.createSequentialGroup()
                        .addComponent(lblMainform, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PNL_drawFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PNL_drawFormLayout.createSequentialGroup()
                                .addComponent(lbl_form_userName)
                                .addGap(0, 0, 0)
                                .addComponent(txtf_formReg_username, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_formReg_usernameERR, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(lbl_form_pass)
                                .addGap(0, 0, 0)
                                .addComponent(JPF_fromReg_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_formReg_passERR, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(lbl_form_passConf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JPF_fromReg_passconf, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_formReg_passconfERR, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PNL_drawFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_form_name)
                                    .addComponent(lbl_form_bornDate)))
                            .addGroup(PNL_drawFormLayout.createSequentialGroup()
                                .addComponent(lbl_form_avatar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_formReg_photoavatar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_formReg_Avatar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PNL_drawFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PNL_drawFormLayout.createSequentialGroup()
                                .addComponent(txtf_formReg_name, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_formReg_nameERR, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(lbl_form_lastName))
                            .addGroup(PNL_drawFormLayout.createSequentialGroup()
                                .addComponent(DC_formReg_borndate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_formReg_borndateERR)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtf_formReg_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_formReg_lastnameERR, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PNL_drawFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_form_email)
                            .addComponent(lbl_form_state))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PNL_drawFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtf_formReg_email, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CB_formReg_state))
                        .addGap(0, 0, 0)
                        .addComponent(lbl_formReg_emailERR, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PNL_drawFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_form_phone)
                            .addComponent(lbl_form_activity))
                        .addGap(0, 0, 0)
                        .addGroup(PNL_drawFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtf_formReg_phone, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                            .addComponent(txt_formReg_activity))
                        .addGap(0, 0, 0)
                        .addGroup(PNL_drawFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_formReg_phoneERR, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_formReg_activityERR))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_form_dni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtf_formReg_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_formReg_dniERR, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PNL_drawFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_formRegCreate_back)
                            .addComponent(btn_formRegCreate_create)))
                    .addGroup(PNL_drawFormLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(PNL_drawForm);

        javax.swing.GroupLayout PNL_formLayout = new javax.swing.GroupLayout(PNL_form);
        PNL_form.setLayout(PNL_formLayout);
        PNL_formLayout.setHorizontalGroup(
            PNL_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNL_formLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                .addContainerGap())
        );
        PNL_formLayout.setVerticalGroup(
            PNL_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNL_formLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE))
        );

        getContentPane().add(PNL_form, java.awt.BorderLayout.CENTER);

        PNL_table.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TABLA_REG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(TABLA_REG);

        javax.swing.GroupLayout PNL_tableLayout = new javax.swing.GroupLayout(PNL_table);
        PNL_table.setLayout(PNL_tableLayout);
        PNL_tableLayout.setHorizontalGroup(
            PNL_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_tableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PNL_tableLayout.setVerticalGroup(
            PNL_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_tableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ANTERIOR.setText("<");
        jPanel3.add(ANTERIOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        SIGUIENTE.setText(">");
        jPanel3.add(SIGUIENTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        CAJA_REG.setEditable(false);
        CAJA_REG.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CAJA_REG.setPreferredSize(new java.awt.Dimension(140, 20));
        jPanel3.add(CAJA_REG, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 80, 30));

        primero.setText("|<");
        jPanel3.add(primero, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        ultimo.setText(">|");
        jPanel3.add(ultimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        btn_tbl_back.setText("V");

        CB_tbl_entries.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "5", "10", "15", "20", "50", "100" }));

        lbl_rowBYpag.setText("Show entries:");

        lbl_filtBY.setText("F");

        lbl_entries.setText("n");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 175, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PNL_mainTablePagerLayout = new javax.swing.GroupLayout(PNL_mainTablePager);
        PNL_mainTablePager.setLayout(PNL_mainTablePagerLayout);
        PNL_mainTablePagerLayout.setHorizontalGroup(
            PNL_mainTablePagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_mainTablePagerLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PNL_mainTablePagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_rowBYpag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PNL_mainTablePagerLayout.createSequentialGroup()
                        .addComponent(CB_tbl_entries, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(PNL_mainTablePagerLayout.createSequentialGroup()
                .addGroup(PNL_mainTablePagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PNL_mainTablePagerLayout.createSequentialGroup()
                        .addComponent(PNL_table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PNL_mainTablePagerLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lbl_filtBY, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_entries, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_tbl_back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(PNL_mainTablePagerLayout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PNL_mainTablePagerLayout.setVerticalGroup(
            PNL_mainTablePagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNL_mainTablePagerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PNL_table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PNL_mainTablePagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PNL_mainTablePagerLayout.createSequentialGroup()
                        .addComponent(lbl_rowBYpag)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CB_tbl_entries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PNL_mainTablePagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_tbl_back)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PNL_mainTablePagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lbl_filtBY, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addComponent(lbl_entries, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(33, 33, 33))
        );

        getContentPane().add(PNL_mainTablePager, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton ANTERIOR;
    public static javax.swing.JTextField CAJA_REG;
    public static javax.swing.JComboBox<String> CB_formReg_state;
    public static javax.swing.JComboBox CB_tbl_entries;
    public static com.toedter.calendar.JDateChooser DC_formReg_borndate;
    public static javax.swing.JPasswordField JPF_fromReg_pass;
    public static javax.swing.JPasswordField JPF_fromReg_passconf;
    public static javax.swing.JPanel PNL_drawForm;
    public static org.edisoncor.gui.panel.PanelImage PNL_footer;
    public static org.edisoncor.gui.panel.PanelImage PNL_form;
    public static javax.swing.JPanel PNL_mainTablePager;
    public static org.edisoncor.gui.panel.PanelImage PNL_menuBtn;
    public static javax.swing.JPanel PNL_table;
    public static org.edisoncor.gui.panel.PanelImage PNL_title;
    public static javax.swing.JButton SIGUIENTE;
    public static javax.swing.JTable TABLA_REG;
    public static javax.swing.ButtonGroup btnGroupState;
    public static org.edisoncor.gui.button.ButtonAero btn_backMain;
    public static javax.swing.JButton btn_createDummies;
    public static javax.swing.JButton btn_createReg;
    public static javax.swing.JButton btn_deleteAllReg;
    public static javax.swing.JButton btn_deleteReg;
    public static javax.swing.JButton btn_formRegCreate_back;
    public static javax.swing.JButton btn_formRegCreate_create;
    public static javax.swing.JButton btn_formReg_Avatar;
    public static javax.swing.JButton btn_modifyReg;
    public static org.edisoncor.gui.button.ButtonAero btn_saveJSON;
    public static org.edisoncor.gui.button.ButtonAero btn_saveTXT;
    public static org.edisoncor.gui.button.ButtonAero btn_saveXML;
    public static javax.swing.JButton btn_tbl_back;
    public static javax.swing.JButton btn_viewReg;
    public static javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel14;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel8;
    public static javax.swing.JPanel jPanel3;
    public static javax.swing.JPanel jPanel4;
    public static javax.swing.JPanel jPanel5;
    public static javax.swing.JPanel jPanel6;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JLabel lblMainform;
    public static javax.swing.JLabel lbl_entries;
    public static javax.swing.JLabel lbl_filtBY;
    public static javax.swing.JLabel lbl_formReg_activityERR;
    public static javax.swing.JLabel lbl_formReg_borndateERR;
    public static javax.swing.JLabel lbl_formReg_dniERR;
    public static javax.swing.JLabel lbl_formReg_emailERR;
    public static javax.swing.JLabel lbl_formReg_lastnameERR;
    public static javax.swing.JLabel lbl_formReg_nameERR;
    public static javax.swing.JLabel lbl_formReg_passERR;
    public static javax.swing.JLabel lbl_formReg_passconfERR;
    public static javax.swing.JLabel lbl_formReg_phoneERR;
    public static javax.swing.JLabel lbl_formReg_photoavatar;
    public static javax.swing.JLabel lbl_formReg_usernameERR;
    public static javax.swing.JLabel lbl_form_activity;
    public static javax.swing.JLabel lbl_form_avatar;
    public static javax.swing.JLabel lbl_form_bornDate;
    public static javax.swing.JLabel lbl_form_dni;
    public static javax.swing.JLabel lbl_form_email;
    public static javax.swing.JLabel lbl_form_lastName;
    public static javax.swing.JLabel lbl_form_name;
    public static javax.swing.JLabel lbl_form_pass;
    public static javax.swing.JLabel lbl_form_passConf;
    public static javax.swing.JLabel lbl_form_phone;
    public static javax.swing.JLabel lbl_form_state;
    public static javax.swing.JLabel lbl_form_userName;
    public static javax.swing.JLabel lbl_rowBYpag;
    public static org.edisoncor.gui.panel.PanelImage panelImage3;
    public static javax.swing.JButton primero;
    public static javax.swing.JTextField txt_formReg_activity;
    public static javax.swing.JTextField txtf_formReg_dni;
    public static javax.swing.JTextField txtf_formReg_email;
    public static javax.swing.JTextField txtf_formReg_lastname;
    public static javax.swing.JTextField txtf_formReg_name;
    public static javax.swing.JTextField txtf_formReg_phone;
    public static javax.swing.JTextField txtf_formReg_username;
    public static javax.swing.JButton ultimo;
    // End of variables declaration//GEN-END:variables
}
