/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package framework.mod.user.admin.view;

import framework.mod.user.admin.model.classes.miniSimpleTableModel_Admin;
import framework.mod.user.admin.model.tools.pager.pagina;
import framework.mod.user.admin.model.BLL.BLL_Admin;
import framework.mod.user.admin.model.DAO.DAO_Admin;
import framework.mod.nav.view.main;
import framework.mod.user.model.clss.singletonU;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author osotemi
 */
public class main_Admin extends javax.swing.JFrame {
    public static TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(new miniSimpleTableModel_Admin());
    //public static AutocompleteJComboBox combo = null;
    /**
     * Creates new main Admin
     */
    public main_Admin() {
        initComponents();
        
        jPanel2.setVisible(false);
        
        ///
        
        DC_formAdm_borndate.getDateEditor().setEnabled(false);
        DC_formAdm_singdate.getDateEditor().setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage3 = new org.edisoncor.gui.panel.PanelImage();
        btnGroupState = new javax.swing.ButtonGroup();
        JPanel_formAdm = new org.edisoncor.gui.panel.PanelImage();
        panelImage5 = new org.edisoncor.gui.panel.PanelImage();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buttonAero4 = new org.edisoncor.gui.button.ButtonAero();
        buttonAero1 = new org.edisoncor.gui.button.ButtonAero();
        buttonAero2 = new org.edisoncor.gui.button.ButtonAero();
        buttonAero3 = new org.edisoncor.gui.button.ButtonAero();
        panelImage8 = new org.edisoncor.gui.panel.PanelImage();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        jPanel2 = new javax.swing.JPanel();
        DC_formAdm_singdate = new com.toedter.calendar.JDateChooser();
        lbl_formAdm_nameERR = new javax.swing.JLabel();
        lbl_formAdm_lastnameERR = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblusernameAdm = new javax.swing.JLabel();
        lbl_formAdm_lusernameERR = new javax.swing.JLabel();
        lbl_formAdm_passERR = new javax.swing.JLabel();
        txtf_formAdm_name = new javax.swing.JTextField();
        txtf_formAdm_email = new javax.swing.JTextField();
        txtf_formAdm_username = new javax.swing.JTextField();
        DC_formAdm_borndate = new com.toedter.calendar.JDateChooser();
        JPF_fromAdm_pass = new javax.swing.JPasswordField();
        btn_formA_Avatar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtf_formAdm_lastname = new javax.swing.JTextField();
        JPF_fromAdm_passconf = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        lbl_formAdm_passconfERR = new javax.swing.JLabel();
        lbllastnameAdm = new javax.swing.JLabel();
        lblnameAdm = new javax.swing.JLabel();
        lbl_formAdm_phoneERR = new javax.swing.JLabel();
        lbl_formAdm_singdateERR = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lbl_formAdm_dniERR = new javax.swing.JLabel();
        lblMainform = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lbl_formAdm_emailERR = new javax.swing.JLabel();
        lblphoneAdm = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lbl_formAdm_borndateERR = new javax.swing.JLabel();
        txtf_formAdm_dni = new javax.swing.JTextField();
        txtf_formAdm_phone = new javax.swing.JTextField();
        CB_formAdm_state = new javax.swing.JComboBox<>();
        txt_formAdm_activity = new javax.swing.JTextField();
        lbl_formAdm_activityERR = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbl_formAdm_photoavatar = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TABLA = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        ANTERIOR = new javax.swing.JButton();
        SIGUIENTE = new javax.swing.JButton();
        CAJA = new javax.swing.JTextField();
        primero = new javax.swing.JButton();
        ultimo = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        javax.swing.GroupLayout panelImage3Layout = new javax.swing.GroupLayout(panelImage3);
        panelImage3.setLayout(panelImage3Layout);
        panelImage3Layout.setHorizontalGroup(
            panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelImage3Layout.setVerticalGroup(
            panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1370, 780));
        setSize(new java.awt.Dimension(1370, 780));

        JPanel_formAdm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/portada-servicios.jpg"))); // NOI18N
        JPanel_formAdm.setName(""); // NOI18N
        JPanel_formAdm.setPreferredSize(new java.awt.Dimension(0, 100));

        javax.swing.GroupLayout JPanel_formAdmLayout = new javax.swing.GroupLayout(JPanel_formAdm);
        JPanel_formAdm.setLayout(JPanel_formAdmLayout);
        JPanel_formAdmLayout.setHorizontalGroup(
            JPanel_formAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1410, Short.MAX_VALUE)
        );
        JPanel_formAdmLayout.setVerticalGroup(
            JPanel_formAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(JPanel_formAdm, java.awt.BorderLayout.NORTH);

        panelImage5.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        buttonAero4.setBackground(new java.awt.Color(255, 0, 0));
        buttonAero4.setText("Inicio");
        buttonAero4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAero4ActionPerformed(evt);
            }
        });

        buttonAero1.setBackground(new java.awt.Color(102, 255, 51));
        buttonAero1.setText("Crear");
        buttonAero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAero1ActionPerformed(evt);
            }
        });

        buttonAero2.setBackground(new java.awt.Color(102, 255, 102));
        buttonAero2.setText("Modificar");
        buttonAero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAero2ActionPerformed(evt);
            }
        });

        buttonAero3.setBackground(new java.awt.Color(153, 255, 102));
        buttonAero3.setText("Borrar");

        javax.swing.GroupLayout panelImage5Layout = new javax.swing.GroupLayout(panelImage5);
        panelImage5.setLayout(panelImage5Layout);
        panelImage5Layout.setHorizontalGroup(
            panelImage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonAero1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelImage5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelImage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(buttonAero4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonAero2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(buttonAero3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelImage5Layout.setVerticalGroup(
            panelImage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonAero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAero3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonAero4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(panelImage5, java.awt.BorderLayout.WEST);

        panelImage8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/framework/img/4809986809_aa94ea96b3_o.jpg"))); // NOI18N
        panelImage8.setPreferredSize(new java.awt.Dimension(1410, 30));

        jLabel4.setForeground(new java.awt.Color(153, 255, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Aviso legal");
        jLabel4.setToolTipText("");

        jLabel5.setForeground(new java.awt.Color(153, 255, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Contactenos");
        jLabel5.setToolTipText("");

        javax.swing.GroupLayout panelImage8Layout = new javax.swing.GroupLayout(panelImage8);
        panelImage8.setLayout(panelImage8Layout);
        panelImage8Layout.setHorizontalGroup(
            panelImage8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImage8Layout.createSequentialGroup()
                .addContainerGap(812, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(192, 192, 192))
        );
        panelImage8Layout.setVerticalGroup(
            panelImage8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelImage8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelImage8, java.awt.BorderLayout.PAGE_END);

        panelImage2.setAutoscrolls(true);
        panelImage2.setMinimumSize(new java.awt.Dimension(0, 0));
        panelImage2.setName(""); // NOI18N
        panelImage2.setPreferredSize(new java.awt.Dimension(500, 600));

        jPanel2.setAutoscrolls(true);
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 535));

        DC_formAdm_singdate.setDateFormatString("dd/MM/yyyy");
        DC_formAdm_singdate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                DC_formAdm_singdatePropertyChange(evt);
            }
        });

        lbl_formAdm_nameERR.setText(" ");

        lbl_formAdm_lastnameERR.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_formAdm_lastnameERR.setText(" ");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Confirmar Contraseña");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Fecha de nacimiento");

        lblusernameAdm.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblusernameAdm.setText("User Name..");

        lbl_formAdm_lusernameERR.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_formAdm_lusernameERR.setText(" ");
        lbl_formAdm_lusernameERR.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lbl_formAdm_passERR.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_formAdm_passERR.setText(" ");

        txtf_formAdm_name.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        txtf_formAdm_name.setText("Nombre...");
        txtf_formAdm_name.setBorder(null);
        txtf_formAdm_name.setNextFocusableComponent(txtf_formAdm_lastname);
        txtf_formAdm_name.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtf_formAdm_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtf_formAdm_nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtf_formAdm_nameFocusLost(evt);
            }
        });
        txtf_formAdm_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtf_formAdm_nameKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtf_formAdm_nameKeyReleased(evt);
            }
        });

        txtf_formAdm_email.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        txtf_formAdm_email.setText("E-mail...");
        txtf_formAdm_email.setBorder(null);
        txtf_formAdm_email.setNextFocusableComponent(txtf_formAdm_phone);
        txtf_formAdm_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtf_formAdm_emailFocusGained(evt);
            }
        });
        txtf_formAdm_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtf_formAdm_emailKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtf_formAdm_emailKeyReleased(evt);
            }
        });

        txtf_formAdm_username.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        txtf_formAdm_username.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtf_formAdm_username.setText("Nombre de usuario...");
        txtf_formAdm_username.setBorder(null);
        txtf_formAdm_username.setNextFocusableComponent(JPF_fromAdm_pass);
        txtf_formAdm_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtf_formAdm_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtf_formAdm_usernameFocusLost(evt);
            }
        });
        txtf_formAdm_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtf_formAdm_usernameKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtf_formAdm_usernameKeyReleased(evt);
            }
        });

        DC_formAdm_borndate.setDateFormatString("dd/MM/yyyy");
        DC_formAdm_borndate.setNextFocusableComponent(txtf_formAdm_username);
        DC_formAdm_borndate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                DC_formAdm_borndatePropertyChange(evt);
            }
        });

        JPF_fromAdm_pass.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        JPF_fromAdm_pass.setBorder(null);
        JPF_fromAdm_pass.setNextFocusableComponent(JPF_fromAdm_passconf);
        JPF_fromAdm_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JPF_fromAdm_passFocusGained(evt);
            }
        });
        JPF_fromAdm_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPF_fromAdm_passActionPerformed(evt);
            }
        });
        JPF_fromAdm_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JPF_fromAdm_passKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JPF_fromAdm_passKeyReleased(evt);
            }
        });

        btn_formA_Avatar.setText("Cargar Imagen");
        btn_formA_Avatar.setBorderPainted(false);
        btn_formA_Avatar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_formA_AvatarActionPerformed(evt);
            }
        });

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Crear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtf_formAdm_lastname.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        txtf_formAdm_lastname.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtf_formAdm_lastname.setText("Apellidos...");
        txtf_formAdm_lastname.setBorder(null);
        txtf_formAdm_lastname.setNextFocusableComponent(txtf_formAdm_email);
        txtf_formAdm_lastname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtf_formAdm_lastnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtf_formAdm_lastnameFocusLost(evt);
            }
        });
        txtf_formAdm_lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtf_formAdm_lastnameActionPerformed(evt);
            }
        });
        txtf_formAdm_lastname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtf_formAdm_lastnameKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtf_formAdm_lastnameKeyReleased(evt);
            }
        });

        JPF_fromAdm_passconf.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        JPF_fromAdm_passconf.setBorder(null);
        JPF_fromAdm_passconf.setNextFocusableComponent(btn_formA_Avatar);
        JPF_fromAdm_passconf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JPF_fromAdm_passconfFocusGained(evt);
            }
        });
        JPF_fromAdm_passconf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPF_fromAdm_passconfActionPerformed(evt);
            }
        });
        JPF_fromAdm_passconf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JPF_fromAdm_passconfKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JPF_fromAdm_passconfKeyReleased(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Contraseña");

        lbl_formAdm_passconfERR.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_formAdm_passconfERR.setText(" ");

        lbllastnameAdm.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbllastnameAdm.setText("Last Name");

        lblnameAdm.setText("Name");

        lbl_formAdm_phoneERR.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_formAdm_phoneERR.setText(" ");

        lbl_formAdm_singdateERR.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_formAdm_singdateERR.setText(" ");

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Fecha de contratación");

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Imagen de perfil");

        jLabel20.setText("Email");

        lbl_formAdm_dniERR.setText(" ");

        lblMainform.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMainform.setText("Formulario de Administrador");

        jLabel22.setText("DNI");

        lbl_formAdm_emailERR.setText(" ");

        lblphoneAdm.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblphoneAdm.setText("Teléfono");

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel26.setText("Estado");

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel27.setText("Actividad");

        lbl_formAdm_borndateERR.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_formAdm_borndateERR.setText(" ");

        txtf_formAdm_dni.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        txtf_formAdm_dni.setText("DNI...");
        txtf_formAdm_dni.setBorder(null);
        txtf_formAdm_dni.setNextFocusableComponent(DC_formAdm_borndate);
        txtf_formAdm_dni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtf_formAdm_dniFocusGained(evt);
            }
        });
        txtf_formAdm_dni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtf_formAdm_dniKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtf_formAdm_dniKeyReleased(evt);
            }
        });

        txtf_formAdm_phone.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        txtf_formAdm_phone.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtf_formAdm_phone.setText("Teléfono...");
        txtf_formAdm_phone.setBorder(null);
        txtf_formAdm_phone.setNextFocusableComponent(txtf_formAdm_dni);
        txtf_formAdm_phone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtf_formAdm_phoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtf_formAdm_phoneFocusLost(evt);
            }
        });
        txtf_formAdm_phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtf_formAdm_phoneKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtf_formAdm_phoneKeyReleased(evt);
            }
        });

        CB_formAdm_state.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Online", "Offline", "Loged" }));
        CB_formAdm_state.setSelectedItem("Offline");
        CB_formAdm_state.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_formAdm_stateActionPerformed(evt);
            }
        });

        txt_formAdm_activity.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_formAdm_activity.setText("0");
        txt_formAdm_activity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_formAdm_activityFocusGained(evt);
            }
        });
        txt_formAdm_activity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_formAdm_activityActionPerformed(evt);
            }
        });
        txt_formAdm_activity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_formAdm_activityKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_formAdm_activityKeyReleased(evt);
            }
        });

        lbl_formAdm_activityERR.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_formAdm_activityERR.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtf_formAdm_name, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtf_formAdm_username, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblnameAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblusernameAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblMainform, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtf_formAdm_email, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl_formAdm_emailERR, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblphoneAdm)
                                        .addComponent(txtf_formAdm_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(JPF_fromAdm_passconf)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(lbl_formAdm_passconfERR, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(lbl_formAdm_photoavatar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(43, 43, 43))))))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lbl_formAdm_nameERR, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lbl_formAdm_lusernameERR, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lbl_formAdm_lastnameERR, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lbl_formAdm_passERR, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lbllastnameAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(txtf_formAdm_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(JPF_fromAdm_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(lbl_formAdm_dniERR, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lbl_formAdm_phoneERR, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtf_formAdm_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(0, 0, Short.MAX_VALUE)))
                                    .addGap(106, 106, 106))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(DC_formAdm_borndate, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn_formA_Avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(218, 218, 218))
                                .addComponent(txt_formAdm_activity, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_formAdm_activityERR, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_formAdm_borndateERR, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(DC_formAdm_singdate, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CB_formAdm_state, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_formAdm_singdateERR, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblMainform, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblnameAdm)
                            .addComponent(lblusernameAdm))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtf_formAdm_username, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtf_formAdm_name))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_formAdm_nameERR, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_formAdm_lusernameERR, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbllastnameAdm)
                            .addComponent(jLabel9))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtf_formAdm_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JPF_fromAdm_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_formAdm_lastnameERR, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_formAdm_passERR, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(0, 0, 0)
                                .addComponent(txtf_formAdm_email, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_formAdm_emailERR, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, 0)
                                .addComponent(JPF_fromAdm_passconf, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_formAdm_passconfERR, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblphoneAdm)
                                .addGap(0, 0, 0)
                                .addComponent(txtf_formAdm_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_formAdm_phoneERR, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtf_formAdm_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_formAdm_photoavatar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(lbl_formAdm_dniERR, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_formA_Avatar)
                    .addComponent(DC_formAdm_borndate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_formAdm_borndateERR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DC_formAdm_singdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CB_formAdm_state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_formAdm_singdateERR, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addGap(1, 1, 1)
                .addComponent(txt_formAdm_activity, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_formAdm_activityERR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelImage2Layout = new javax.swing.GroupLayout(panelImage2);
        panelImage2.setLayout(panelImage2Layout);
        panelImage2Layout.setHorizontalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        panelImage2Layout.setVerticalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImage2Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                .addGap(229, 229, 229))
        );

        getContentPane().add(panelImage2, java.awt.BorderLayout.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TABLA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(TABLA);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ANTERIOR.setText("<");
        ANTERIOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANTERIORActionPerformed(evt);
            }
        });
        jPanel3.add(ANTERIOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        SIGUIENTE.setText(">");
        SIGUIENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIGUIENTEActionPerformed(evt);
            }
        });
        jPanel3.add(SIGUIENTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        CAJA.setEditable(false);
        CAJA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CAJA.setPreferredSize(new java.awt.Dimension(140, 20));
        jPanel3.add(CAJA, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 80, 30));

        primero.setText("|<");
        primero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeroActionPerformed(evt);
            }
        });
        jPanel3.add(primero, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        ultimo.setText(">|");
        ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ultimoActionPerformed(evt);
            }
        });
        jPanel3.add(ultimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 761, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        jButton3.setText("Volver");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "5", "10", "15", "20", "50", "100" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel11.setText("Show entries:");

        jLabel12.setText("Filtra First Name");

        jLabel13.setText("jLabel3");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 205, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                            .addGap(7, 7, 7)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(33, 33, 33))
        );

        getContentPane().add(jPanel7, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAero2ActionPerformed
        BLL_Admin.BLL_ModifyAdm();
    }//GEN-LAST:event_buttonAero2ActionPerformed

    private void buttonAero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAero1ActionPerformed
        BLL_Admin.BLL_Adm_form();
    }//GEN-LAST:event_buttonAero1ActionPerformed

    private void buttonAero4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAero4ActionPerformed
        this.dispose();
        BLL_Admin.BLL_FA_mainBack();
    }//GEN-LAST:event_buttonAero4ActionPerformed

    private void JPF_fromAdm_passconfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPF_fromAdm_passconfActionPerformed
        BLL_Admin.BLL_JPF_PassConfirm();
    }//GEN-LAST:event_JPF_fromAdm_passconfActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        BLL_Admin.BLL_FA_HideNewFormPanel();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_formA_AvatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_formA_AvatarActionPerformed
        BLL_Admin.BLL_Avatar();
    }//GEN-LAST:event_btn_formA_AvatarActionPerformed

    private void JPF_fromAdm_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPF_fromAdm_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPF_fromAdm_passActionPerformed

    private void CB_formAdm_stateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_formAdm_stateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_formAdm_stateActionPerformed

    private void txtf_formAdm_lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtf_formAdm_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf_formAdm_lastnameActionPerformed

    private void txtf_formAdm_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtf_formAdm_nameFocusLost
        BLL_Admin.BLL_txtName();
    }//GEN-LAST:event_txtf_formAdm_nameFocusLost

    private void txtf_formAdm_nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_formAdm_nameKeyTyped
        BLL_Admin.BLL_txtName();
    }//GEN-LAST:event_txtf_formAdm_nameKeyTyped

    private void txtf_formAdm_lastnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtf_formAdm_lastnameFocusGained
        BLL_Admin.BLL_FA_CleanLastName();
    }//GEN-LAST:event_txtf_formAdm_lastnameFocusGained

    private void txtf_formAdm_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtf_formAdm_nameFocusGained
        BLL_Admin.BLL_FA_CleanName();
    }//GEN-LAST:event_txtf_formAdm_nameFocusGained

    private void txtf_formAdm_lastnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_formAdm_lastnameKeyTyped
        BLL_Admin.BLL_txtLastname();
    }//GEN-LAST:event_txtf_formAdm_lastnameKeyTyped

    private void txtf_formAdm_lastnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtf_formAdm_lastnameFocusLost
        BLL_Admin.BLL_txtLastname();
    }//GEN-LAST:event_txtf_formAdm_lastnameFocusLost

    private void txtf_formAdm_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtf_formAdm_usernameFocusGained
        BLL_Admin.BLL_FA_CleanUserName();
    }//GEN-LAST:event_txtf_formAdm_usernameFocusGained

    private void txtf_formAdm_usernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_formAdm_usernameKeyTyped
        BLL_Admin.BLL_txtUsername();
    }//GEN-LAST:event_txtf_formAdm_usernameKeyTyped

    private void txtf_formAdm_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtf_formAdm_usernameFocusLost
        BLL_Admin.BLL_txtUsername();
    }//GEN-LAST:event_txtf_formAdm_usernameFocusLost

    private void txtf_formAdm_phoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtf_formAdm_phoneFocusGained
        BLL_Admin.BLL_FA_CleanPhone();
    }//GEN-LAST:event_txtf_formAdm_phoneFocusGained

    private void txtf_formAdm_phoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_formAdm_phoneKeyTyped
        BLL_Admin.BLL_txtPhone();
    }//GEN-LAST:event_txtf_formAdm_phoneKeyTyped

    private void txtf_formAdm_phoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtf_formAdm_phoneFocusLost
        BLL_Admin.BLL_txtPhone();
    }//GEN-LAST:event_txtf_formAdm_phoneFocusLost

    private void txtf_formAdm_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_formAdm_nameKeyReleased
        BLL_Admin.BLL_txtName();
    }//GEN-LAST:event_txtf_formAdm_nameKeyReleased

    private void txtf_formAdm_lastnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_formAdm_lastnameKeyReleased
        BLL_Admin.BLL_txtLastname();
    }//GEN-LAST:event_txtf_formAdm_lastnameKeyReleased

    private void txtf_formAdm_usernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_formAdm_usernameKeyReleased
        BLL_Admin.BLL_txtUsername();
    }//GEN-LAST:event_txtf_formAdm_usernameKeyReleased

    private void txtf_formAdm_phoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_formAdm_phoneKeyReleased
        BLL_Admin.BLL_txtPhone();
    }//GEN-LAST:event_txtf_formAdm_phoneKeyReleased

    private void JPF_fromAdm_passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JPF_fromAdm_passFocusGained
        BLL_Admin.BLL_JPF_Password();
    }//GEN-LAST:event_JPF_fromAdm_passFocusGained

    private void JPF_fromAdm_passKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JPF_fromAdm_passKeyTyped
        BLL_Admin.BLL_JPF_Password();
    }//GEN-LAST:event_JPF_fromAdm_passKeyTyped

    private void JPF_fromAdm_passKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JPF_fromAdm_passKeyReleased
        BLL_Admin.BLL_JPF_Password();
    }//GEN-LAST:event_JPF_fromAdm_passKeyReleased

    private void JPF_fromAdm_passconfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JPF_fromAdm_passconfFocusGained
        BLL_Admin.BLL_JPF_PassConfirm();
    }//GEN-LAST:event_JPF_fromAdm_passconfFocusGained

    private void JPF_fromAdm_passconfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JPF_fromAdm_passconfKeyTyped
        BLL_Admin.BLL_JPF_PassConfirm();
    }//GEN-LAST:event_JPF_fromAdm_passconfKeyTyped

    private void JPF_fromAdm_passconfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JPF_fromAdm_passconfKeyReleased
        BLL_Admin.BLL_JPF_PassConfirm();
    }//GEN-LAST:event_JPF_fromAdm_passconfKeyReleased

    private void txtf_formAdm_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtf_formAdm_emailFocusGained
        BLL_Admin.BLL_FA_CleanEmail();
    }//GEN-LAST:event_txtf_formAdm_emailFocusGained

    private void txtf_formAdm_emailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_formAdm_emailKeyTyped
        BLL_Admin.BLL_txtEmail();
    }//GEN-LAST:event_txtf_formAdm_emailKeyTyped

    private void txtf_formAdm_emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_formAdm_emailKeyReleased
        BLL_Admin.BLL_txtEmail();
    }//GEN-LAST:event_txtf_formAdm_emailKeyReleased

    private void txtf_formAdm_dniFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtf_formAdm_dniFocusGained
        BLL_Admin.BLL_FA_CleanDNI();
    }//GEN-LAST:event_txtf_formAdm_dniFocusGained

    private void txtf_formAdm_dniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_formAdm_dniKeyTyped
        BLL_Admin.BLL_txtDNI();
    }//GEN-LAST:event_txtf_formAdm_dniKeyTyped

    private void txtf_formAdm_dniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_formAdm_dniKeyReleased
        BLL_Admin.BLL_txtDNI();
    }//GEN-LAST:event_txtf_formAdm_dniKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        BLL_Admin.BLL_FA_CreateAdmin();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void DC_formAdm_borndatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_DC_formAdm_borndatePropertyChange
        BLL_Admin.BLL_DCBornDate();
    }//GEN-LAST:event_DC_formAdm_borndatePropertyChange

    private void DC_formAdm_singdatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_DC_formAdm_singdatePropertyChange
        BLL_Admin.BLL_DCSingDate();
    }//GEN-LAST:event_DC_formAdm_singdatePropertyChange

    private void txt_formAdm_activityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_formAdm_activityActionPerformed
        BLL_Admin.BLL_Activity();
    }//GEN-LAST:event_txt_formAdm_activityActionPerformed

    private void txt_formAdm_activityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_formAdm_activityFocusGained
        BLL_Admin.BLL_Activity();
    }//GEN-LAST:event_txt_formAdm_activityFocusGained

    private void txt_formAdm_activityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_formAdm_activityKeyTyped
        BLL_Admin.BLL_Activity();
    }//GEN-LAST:event_txt_formAdm_activityKeyTyped

    private void txt_formAdm_activityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_formAdm_activityKeyReleased
        BLL_Admin.BLL_Activity();
    }//GEN-LAST:event_txt_formAdm_activityKeyReleased

    private void ANTERIORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANTERIORActionPerformed
        pagina.currentPageIndex -= 1;
        pagina.initLinkBox();
    }//GEN-LAST:event_ANTERIORActionPerformed

    private void SIGUIENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIGUIENTEActionPerformed
        pagina.currentPageIndex += 1;
        pagina.initLinkBox();
    }//GEN-LAST:event_SIGUIENTEActionPerformed

    private void primeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeroActionPerformed
        pagina.currentPageIndex = 1;
        pagina.initLinkBox();
    }//GEN-LAST:event_primeroActionPerformed

    private void ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ultimoActionPerformed
        pagina.currentPageIndex = pagina.maxPageIndex;
        pagina.initLinkBox();
    }//GEN-LAST:event_ultimoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        //new menu().setVisible(true);        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        pagina.itemsPerPage=Integer.parseInt(jComboBox1.getSelectedItem().toString());
        pagina.currentPageIndex = 1;
        pagina.initLinkBox();
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton ANTERIOR;
    public static javax.swing.JTextField CAJA;
    public static javax.swing.JComboBox<String> CB_formAdm_state;
    public static com.toedter.calendar.JDateChooser DC_formAdm_borndate;
    public static com.toedter.calendar.JDateChooser DC_formAdm_singdate;
    public static javax.swing.JPasswordField JPF_fromAdm_pass;
    public static javax.swing.JPasswordField JPF_fromAdm_passconf;
    public static org.edisoncor.gui.panel.PanelImage JPanel_formAdm;
    public static javax.swing.JButton SIGUIENTE;
    public static javax.swing.JTable TABLA;
    public static javax.swing.ButtonGroup btnGroupState;
    public static javax.swing.JButton btn_formA_Avatar;
    public static org.edisoncor.gui.button.ButtonAero buttonAero1;
    public static org.edisoncor.gui.button.ButtonAero buttonAero2;
    public static org.edisoncor.gui.button.ButtonAero buttonAero3;
    public static org.edisoncor.gui.button.ButtonAero buttonAero4;
    public static javax.swing.JButton jButton1;
    public static javax.swing.JButton jButton2;
    public static javax.swing.JButton jButton3;
    public static javax.swing.JComboBox jComboBox1;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel11;
    public static javax.swing.JLabel jLabel12;
    public static javax.swing.JLabel jLabel13;
    public static javax.swing.JLabel jLabel17;
    public static javax.swing.JLabel jLabel19;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel20;
    public static javax.swing.JLabel jLabel22;
    public static javax.swing.JLabel jLabel26;
    public static javax.swing.JLabel jLabel27;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel jLabel9;
    public static javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPanel2;
    public static javax.swing.JPanel jPanel3;
    public static javax.swing.JPanel jPanel4;
    public static javax.swing.JPanel jPanel5;
    public static javax.swing.JPanel jPanel6;
    public static javax.swing.JPanel jPanel7;
    public static javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JLabel lblMainform;
    public static javax.swing.JLabel lbl_formAdm_activityERR;
    public static javax.swing.JLabel lbl_formAdm_borndateERR;
    public static javax.swing.JLabel lbl_formAdm_dniERR;
    public static javax.swing.JLabel lbl_formAdm_emailERR;
    public static javax.swing.JLabel lbl_formAdm_lastnameERR;
    public static javax.swing.JLabel lbl_formAdm_lusernameERR;
    public static javax.swing.JLabel lbl_formAdm_nameERR;
    public static javax.swing.JLabel lbl_formAdm_passERR;
    public static javax.swing.JLabel lbl_formAdm_passconfERR;
    public static javax.swing.JLabel lbl_formAdm_phoneERR;
    public static javax.swing.JLabel lbl_formAdm_photoavatar;
    public static javax.swing.JLabel lbl_formAdm_singdateERR;
    public static javax.swing.JLabel lbllastnameAdm;
    public static javax.swing.JLabel lblnameAdm;
    public static javax.swing.JLabel lblphoneAdm;
    public static javax.swing.JLabel lblusernameAdm;
    public static org.edisoncor.gui.panel.PanelImage panelImage2;
    public static org.edisoncor.gui.panel.PanelImage panelImage3;
    public static org.edisoncor.gui.panel.PanelImage panelImage5;
    public static org.edisoncor.gui.panel.PanelImage panelImage8;
    public static javax.swing.JButton primero;
    public static javax.swing.JTextField txt_formAdm_activity;
    public static javax.swing.JTextField txtf_formAdm_dni;
    public static javax.swing.JTextField txtf_formAdm_email;
    public static javax.swing.JTextField txtf_formAdm_lastname;
    public static javax.swing.JTextField txtf_formAdm_name;
    public static javax.swing.JTextField txtf_formAdm_phone;
    public static javax.swing.JTextField txtf_formAdm_username;
    public static javax.swing.JButton ultimo;
    // End of variables declaration//GEN-END:variables
}
